### ISSUE TITLE
Passing object to format method prints, [object Object]

### ISSUE THREAD

**Issue by madhavan020985** [davidchambers/string-format#8]
````javascript
> var format = require('string-format')
> format.extend(String.prototype)
> var obj = {"name" :"saran"}
> "hai, i am, {0}".format(obj)
'hai, i am [object Object]'
````

In the last line, it is good to have a stringified representation of the JSON object instead of printing `[object Object]`.

The desired output is,
hai, i am, {"name" :"saran"}

**Comment by davidchambers** [comment]
You could define a custom [transformer][1]:

```javascript
format.extend(String.prototype, {repr: JSON.stringify});
```

```javascript
> 'hai, i am {0!repr}'.format({name: 'saran'})
'hai, i am {"name":"saran"}'
```

[`R.toString`][2] provides nicer string representations in many cases than `JSON.stringify` does:

```javascript
const R = require('ramda');

format.extend(String.prototype, {repr: R.toString});
```

```javascript
> 'hai, i am {0!repr}'.format({name: 'saran'})
'hai, i am {"name": "saran"}'
```

I don't think we should change the default behaviour. It's currently very easy to explain: we use a value's string representation as determined by `String(<value>)`. Were we to use `JSON.stringify(<value>)` instead, `'Hello {name}'.format({name: 'Alice'})` would give `'Hello "Alice"'` rather than `'Hello Alice'`, and custom `toString` methods would be ignored. We could use `JSON.stringify` or a similar function only if `<value>.toString === Object.prototype.toString`, but such magic makes functions more difficult to reason about.

Let me know your thoughts. :)


[1]: https://github.com/davidchambers/string-format/tree/0.5.0#formatextendprototype-transformers
[2]: http://ramdajs.com/docs/#toString

**Comment by madhavan020985** [comment]
if there is a way around it, then it is good to go...
however, the conversion of object to str, can it be hidden from the developer..

like, say ob is an object and st is a string, and i am printing both as,
````javascript
 obj = {"key" : "value"}, and st = "hello"
//as you suggest, it can be printed as,
console.log("i am an object, {0!repr}  and i am a string {1}".format(obj, st))
//can i do this as well, so i need not worry about me, doing conversions manually?????
console.log("i am an object, {0}  and i am a string {1}".format(obj, st))
````

**Comment by madhavan020985** [comment]
hey, wat abt this,
````javascript
Object.prototype.toString() = {
  return JSON.stringify(this) //or even R.toString()
}
````
Object object is no way a useful info, and i can live without it

**Comment by davidchambers** [comment]
> hey, wat abt this,
>
> ```javascript
> Object.prototype.toString() = {
>   return JSON.stringify(this) //or even R.toString()
> }
> ```

That's a creative solution. So long as you understand that you'll break code which relies on the default behaviour of `Object.prototype.toString`, this could work.
